[build]
  command = "yarn build"
  functions = "functions"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions.mintTimeCapsule]
  external_node_modules = ["chrome-aws-lambda"]
