[build]
  command = "yarn build"
  publish = ".next"
  functions = "built-functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "built-functions"
  node_bundler = "esbuild"

[functions.postTimeCapsule]
  external_node_modules = ["chrome-aws-lambda"]
