import type { NextPage } from 'next';
import Head from 'next/head';
import { Card, Container } from '@mantine/core';
import { useMediaQuery } from '@mantine/hooks';
import { MintForm } from '../components/MintForm';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const isMobile = useMediaQuery('(max-width: 599px)');

  return (
    <Container px="0">
      <Head>
        <title>Centrifuge Time Capsule</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container size="md" px="0" className={styles['mint-container']}>
        {isMobile ? (
          <Container px="24px" mx={0} pt="48px">
            <MintForm />
          </Container>
        ) : (
          <Card shadow="md" className={styles['mint-card']}>
            <MintForm />
          </Card>
        )}
      </Container>
    </Container>
  );
};

export default Home;
