import type { NextPage } from 'next';
import Head from 'next/head';
import { useForm, SubmitHandler } from 'react-hook-form';
import useMintTimeCapsule from '../hooks/useMintTimeCapsule';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();

  const { mutate, data } = useMintTimeCapsule();

  const onSubmit: SubmitHandler<Inputs> = data => mutate(data);

  if (data) {
    return <div>Success! Your address is {data.nftAddress}</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Centrifuge Time Capsule</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <input
            placeholder="0x71C7656EC7ab88b098defB751B7401B5f6d8976F"
            {...register('maticAddress', { required: true })}
          />
          {errors.maticAddress && <span>This field is required</span>}

          <input
            placeholder="@elon_musk"
            {...register('twitterHandle', { required: true })}
          />
          {errors.twitterHandle && <span>This field is required</span>}

          <input
            placeholder="In 2023..."
            {...register('prediction', { required: true })}
          />
          {errors.prediction && <span>This field is required</span>}

          <button type="submit">Mint NFT</button>
        </form>
      </div>
    </div>
  );
};

export default Home;
