import type { NextPage } from 'next';
import Head from 'next/head';
import { Container } from '@mantine/core';
import { useMediaQuery } from '@mantine/hooks';
import DOMParserReact from 'dom-parser-react';
import styles from '../styles/Home.module.css';
import useGetTimeCapsules from '../hooks/useGetTimeCapsules';
import { TimeCapsule } from '../types';

const Home: NextPage = () => {
  const isMobile = useMediaQuery('(max-width: 599px)');

  const { data, isLoading } = useGetTimeCapsules();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <Container px="0">
      <Head>
        <title>Centrifuge Time Capsule</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container size="md" px="0" className={styles['mint-container']}>
        {isMobile ? (
          <Container px="24px" mx={0} pt="48px">
            Cards
          </Container>
        ) : (
          data.map(({ id, svg }: TimeCapsule) => (
            <DOMParserReact key={id} source={svg} />
          ))
        )}
      </Container>
    </Container>
  );
};

export default Home;
